# Generated by Django 4.2.6 on 2023-10-17 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('condition', models.CharField(choices=[('newbies', 'newbies'), ('orders', 'orders'), ('amount', 'amount'), ('product', 'product'), ('shipping', 'shipping')], max_length=20)),
                ('discount_type', models.CharField(choices=[('PCT', 'PCT'), ('AMT', 'AMT')], default='PCT', max_length=3)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('min_orders', models.IntegerField(default=0)),
                ('total_coupons', models.IntegerField()),
                ('available_coupons', models.IntegerField(default=-1)),
                ('no_times', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
