# Generated by Django 4.2.6 on 2023-10-17 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=25)),
                ('account_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleIncome',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income_for', models.CharField(choices=[('admin', 'admin'), ('vendor', 'vendor')], max_length=8)),
                ('user', models.UUIDField(blank=True, null=True)),
                ('transaction_ref', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('refunded', 'refunded')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
