# Generated by Django 4.2.6 on 2023-10-17 11:09

from django.db import migrations, models
import order.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_id', models.CharField(default=order.utils.generate_order_id, editable=False, max_length=15)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('order_placed', 'order_placed'), ('order_confirmed', 'order_confirmed'), ('processed', 'processed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('order_returned', 'order_returned'), ('refunded', 'refunded')], default='pending', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_method', models.JSONField(blank=True, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('refunded_date', models.DateTimeField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ordered', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('order_placed', 'order_placed'), ('order_confirmed', 'order_confirmed'), ('processed', 'processed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('order_returned', 'order_returned'), ('refunded', 'refunded')], default='pending', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('refunded_date', models.DateTimeField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
